#!/bin/bash

# Ubuntu 16.04 LTS, 18.04 LTS 
# https://about.gitlab.com/install/#ubuntu

DOMAIN_NAME="https://gitlab.example.com"

# 信任 GitLab 的 GPG 公钥
curl https://packages.gitlab.com/gpg.key 2> /dev/null | sudo apt-key add - &>/dev/null

# 配置清华源
cat > /etc/apt/sources.list.d/gitlab_gitlab-ce.list <<EOF
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce
# 原镜像
# deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main
# deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main
# 清华镜像
deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic main
deb-src https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic main
EOF

sudo apt-get update
sudo apt-get install -y curl openssh-server ca-certificates

sudo apt-get install -y postfix
# 选择“Internet Site”并按Enter键。

sudo apt-get install gitlab-ce

# config

sed -i "s@# external_url.*@external_url '${DOMAIN_NAME}'@g" /etc/gitlab/gitlab.rb

