#!/bin/bash

# Ubuntu 16.04 LTS, 18.04 LTS 
# https://about.gitlab.com/install/#ubuntu

DOMAIN_NAME="https://gitlab.example.com"
NGINX_USER="nginx"

# 信任 GitLab 的 GPG 公钥
curl https://packages.gitlab.com/gpg.key 2> /dev/null | sudo apt-key add - &>/dev/null

# 配置清华源
cat > /etc/apt/sources.list.d/gitlab_gitlab-ce.list <<EOF
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce
# 原镜像
# deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main
# deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main
# 清华镜像
deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic main
deb-src https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic main
EOF

sudo apt-get update
sudo apt-get install -y curl openssh-server ca-certificates

sudo apt-get install -y postfix
# 选择“Internet Site”并按Enter键。

sudo apt-get install gitlab-ce

# config
# 配置域名
sed -i "/^external_url/s/gitlab.example.com/${DOMAIN_NAME}/" /etc/gitlab/gitlab.rb

# 使用外部nginx
sed -i "s/^# nginx\['enable'\] =.*/nginx\['enable'\] = false/"  /etc/gitlab/gitlab.rb
sed -i "s/# web_server\['external_users'\] = .*/web_server\['external_users'\] = ${NGINX_USER}/"  /etc/gitlab/gitlab.rb
